### ISSUE TITLE
Various errata from 1.1

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-schema#2]
From [RDF 1.1 Errata](https://www.w3.org/2001/sw/wiki/RDF1.1_Errata):

* [x] [15 – Markup & display bug](https://www.w3.org/2001/sw/wiki/RDF1.1_Errata#erratum_15)
* [x] [31 – Inconsistent description of the domain of rdf:property](https://www.w3.org/2001/sw/wiki/RDF1.1_Errata#erratum_31)

**Comment by timothee-haudebourg** [comment]
It seems like Errata 15 is fixed by #5 and Errata 31 is closed by #15. We can close this issue then, please reopen it if I'm wrong.
