### ISSUE TITLE
The "Latest Recommendation" link is the latest WD tracking link.

### ISSUE THREAD

**Issue by afs** [w3c/rdf-schema#20]
Reported on Twitter.

**Comment by namedgraph** [comment]
https://www.w3.org/TR/rdf-schema still leads to 1.2 WD

**Comment by namedgraph** [comment]
@afs where is the https://www.w3.org/TR/rdf11-schema document? It's not available.

**Comment by afs** [comment]
https://www.w3.org/TR/2014/REC-rdf-schema-20140225/
