### ISSUE TITLE
Update `spec/common/participants.html` file

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/rdf-schema#6]
There is still an issue with my name in this file. @gkellogg I could re-generate it, but wouldn't it be better to have `common` be a submodule used by all the RDF 1.2 repositories?

**Comment by gkellogg** [comment]
I updated in PR #5.

**Comment by TallTed** [comment]
@gkellogg 
> the contents need to be synchronized manually

I wonder whether a GitHub Action could be used to automate this sync? (I know GitHub Actions exist and seem like they should work for this, but I know virtually nothing about using them, so I cannot provide more details on this thought.)

**Comment by Tpt** [comment]
> I wonder whether a GitHub Action could be used to automate this sync? (I know GitHub Actions exist and seem like they should work for this, but I know virtually nothing about using them, so I cannot provide more details on this thought.)

It should definitely be possible if a W3G GitHub organization admin is ok to create an access token to all RDF and SPARQL repositories. Thee [the doc](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions).

**Comment by gkellogg** [comment]
It is possible, and I’m working on something similar for RCH, but haven’t gotten there yet. It will require coordination on repo settings. The current action that checks for consistency could potentially be updated to commit changed files, instead.
