### ISSUE TITLE
Add the rdf:JSON datatype

### ISSUE THREAD

**Issue by domel** [w3c/rdf-schema#7]
Dependence on https://github.com/w3c/rdf-concepts/issues/14

**Comment by TallTed** [comment]
@domel — It would be helpful if you could put a bit more detail into the Issues and PRs you raise. `rdf:JSON` is not a clear statement of the issue at hand here, and the note that this "[depends] on https://github.com/w3c/rdf-concepts/issues/14" does not suggest that useful detail will be found there, rather that the resolution of this (indeterminate) issue will depend on the resolution of that issue, which remains unresolved at this writing, making the possible resolution of this issue in PR #7 premature at best.

**Comment by domel** [comment]
@TallTed Everything has already been written in https://github.com/w3c/rdf-concepts/issues/14. But I will try to refer more to RDF Schema spec. [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/#the-rdf-json-datatype) defined `rdf:JSON`. The mentioned datatype was also added in `http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON`.So now we have some dissonance. RDF Schema 1.1 spec, which describes `rdf` (and `rdfs`) namespaces, do not mention `rdf:RDF` despite the fact that it is in the vocabulary. Moreover, there are a few implementations of `rdf:JSON` (e.g., Ruby RDF, dotNetRDF, etc). To sum up, RDF(S) vocab has the datatype, RDFS spec hasn't, RDF Concepts spec hasn't.

**Comment by gkellogg** [comment]
Maybe if the issue title were updated here (and in RDF Concepts) to something like "Add the `rdf:JSON` datatype` it would be more clear.
